### ISSUE TITLE
Doesn't Click scrolls

### ISSUE THREAD

**Issue by zombidle** [cottiAC/zombidleBot#3] opened 2017-06-11 00:01 UTC
Im having a problem where is doesn't collect the scrolls, any idea what's causing this?

**Comment by JourneyOver** [comment] 2017-06-11 12:53
What platform are you playing on? steam or web

if on steam platform are you using the steam release version, and what resolution are you running the game at?

There is a known bug with mouse click events (bug with the game not with the bot) that could be the cause of this as well, but I haven't run into it not collecting the scrolls just issues with clicking on the buttons for the actual scroll usage which is noted in [my issue](https://github.com/cottiAC/zombidleBot/issues/2).

**Comment by zombidle** [comment] 2017-06-11 17:51
Playing on steam at 1136x640 res

**Comment by JourneyOver** [comment] 2017-06-11 18:16
hmm playing on the HD graphics or the SD graphics?

**Comment by zombidle** [comment] 2017-06-11 20:19
Playing on HD graphics

**Comment by JourneyOver** [comment] 2017-06-11 20:22
Try playing on SD and see if that works for you (as that's what works for me). I don't think the bot supports HD in any shape or form.

**Comment by zombidle** [comment] 2017-06-11 20:31
Thanks that seems to fix it!

**Comment by JourneyOver** [comment] 2017-06-11 20:42
Glad to hear! be warned you may need to babysit the bot a slight bit if you do want it to use scrolls because there is a chance that it could get stuck while doing a scroll due to the bug I mentioned above.

**Comment by zombidle** [comment] 2017-06-11 20:44
It clicks yes to scrolls just fine, but it just picked a chest but gets stuck when selecting an item. Do u know if it's possible to click "no" to chest scrolls?

**Comment by JourneyOver** [comment] 2017-06-11 21:01
trust me you'll run into it as I have several times and so has one of my friends, and chests are currently not supported (both world map ones nor scroll ones) so they have to be done manually, there is currently no way for the bot to click "no" at the moment on any of the scrolls. @cottiAC should have something implemented soonish though that you'll be able to choose what scrolls you want to take or not.

**Comment by zombidle** [comment] 2017-06-11 21:03
Alright, thanks for the help.

**Comment by JourneyOver** [comment] 2017-06-11 21:09
Since this has been handled you can close this, just click on the "close issue" unless you want cottiAC to close it for you next time they are on.

**Closed as completed** 2017-06-11 21:12 UTC
